trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  GOPATH: '$(Agent.BuildDirectory)/gopath' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GO111MODULE: 'on' 
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: go get sigs.k8s.io/kind@v0.4.0
  displayName: 'Install kind'

- script: $(GOBIN)/kind create cluster
  displayName: 'Deploying kind cluster'

- script: export KUBECONFIG="$($(GOBIN)/kind get kubeconfig-path --name="kind")" && kubectl cluster-info
  displayName: 'Show cluster info'