trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: GO111MODULE="on" go get sigs.k8s.io/kind@v0.4.0
  displayName: 'Install kind'

- script: kind create cluster
  displayName: 'Deploying kind cluster'

- script: export KUBECONFIG="$(kind get kubeconfig-path --name="kind")" && kubectl cluster-info
  displayName: 'Show cluster info'